### ISSUE TITLE
Class names?

### ISSUE THREAD

**Issue by basilevh** [saykartik/assemblies#10]
Based on Brett's diagram shown below, it is a little bit confusing to have classes called Form1, Form2, Form3, Form4 etc.

Perhaps we should give them names? I'd have no problem with FFLocalTableFractionNet and FFLocalTablePercentageNet for example; up to you.

[FeedForward Class Hierarchy.pdf](https://github.com/saykartik/assemblies/files/5570324/FeedForward.Class.Hierarchy.pdf)

**Comment by BKaropczyc** [comment]
Ok - I'll update with more descriptive name tonight.

**Comment by BKaropczyc** [comment]
Renamed classes and files for improved readability.
