### ISSUE TITLE
Layer-dependent Rules for Feedforward Neural Network

### ISSUE THREAD

**Issue by basilevh** [saykartik/assemblies#11]
Instead of a universal rule, allow classes to be instantiated with multiple rules, one for each hidden layer. I will modify @BKaropczyc 's classes to that end this weekend (unless he specifically wants to take over).

**Comment by basilevh** [comment]
actually I have enough work for the time being, changing assignee to @BKaropczyc since you're more familiar with the code

**Comment by BKaropczyc** [comment]
I've got some ideas of how to redesign the class hierarchy to accomplish this, but it might be a major update. Still need to flesh out the ideas. May develop on a branch...

**Comment by BKaropczyc** [comment]
Taking lack of response on WhatsApp as tacit support for merging these changes into the Master branch.
